## pip install e import das libs

In [ ]:
!pip install datetime
!pip install numpy
!pip install pandas
!pip install torch
!pip install tensordict

Collecting datetime
  Downloading DateTime-5.5-py3-none-any.whl.metadata (33 kB)
Collecting zope.interface (from datetime)
  Downloading zope.interface-7.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 5.4 MB/s eta 0:00:00
Requirement already satisfied: pytz in ./venv/lib/python3.12/site-packages (from datetime) (2025.2)
Requirement already satisfied: setuptools in ./venv/lib/python3.12/site-packages (from zope.interface->datetime) (80.9.0)
Downloading DateTime-5.5-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 7.7 MB/s eta 0:00:00
Downloading zope.interface-7.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.7/264.7 kB 14.2 MB/s eta 0:00:00
Installing collected packages: zope.interface, datetime
Successfully installed datetime-5.5 zope.interface-7.2
Requirement already satisfied: numpy in ./venv/lib/python3.12/site-packages (2.2.6)
Requirement already satisfied: pandas in ./venv/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.12/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: torch in ./venv/lib/python3.12/site-packages (2.7.0)
Requirement already satisfied: filelock in ./venv/lib/python3.12/site-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in ./venv/lib/python3.12/site-packages (from torch) (4.14.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.12/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./venv/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in ./venv/lib/python3.12/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in ./venv/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in ./venv/lib/python3.12/site-packages (from torch) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in ./venv/lib/python3.12/site-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in ./venv/lib/python3.12/site-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in ./venv/lib/python3.12/site-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in ./venv/lib/python3.12/site-packages (from torch) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in ./venv/lib/python3.12/site-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in ./venv/lib/python3.12/site-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in ./venv/lib/python3.12/site-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in ./venv/lib/python3.12/site-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in ./venv/lib/python3.12/site-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in ./venv/lib/python3.12/site-packages (from torch) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in ./venv/lib/python3.12/site-packages (from torch) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in ./venv/lib/python3.12/site-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in ./venv/lib/python3.12/site-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in ./venv/lib/python3.12/site-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.3.0 in ./venv/lib/python3.12/site-packages (from torch) (3.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.12/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: tensordict in ./venv/lib/python3.12/site-packages (0.8.3)
Requirement already satisfied: torch in ./venv/lib/python3.12/site-packages (from tensordict) (2.7.0)
Requirement already satisfied: numpy in ./venv/lib/python3.12/site-packages (from tensordict) (2.2.6)
Requirement already satisfied: cloudpickle in ./venv/lib/python3.12/site-packages (from tensordict) (3.1.1)
Requirement already satisfied: packaging in ./venv/lib/python3.12/site-packages (from tensordict) (25.0)
Requirement already satisfied: importlib_metadata in ./venv/lib/python3.12/site-packages (from tensordict) (8.7.0)
Requirement already satisfied: orjson in ./venv/lib/python3.12/site-packages (from tensordict) (3.10.18)
Requirement already satisfied: zipp>=3.20 in ./venv/lib/python3.12/site-packages (from importlib_metadata->tensordict) (3.22.0)
Requirement already satisfied: filelock in ./venv/lib/python3.12/site-packages (from torch->tensordict) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (4.14.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.12/site-packages (from torch->tensordict) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (1.14.0)
Requirement already satisfied: networkx in ./venv/lib/python3.12/site-packages (from torch->tensordict) (3.5)
Requirement already satisfied: jinja2 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (3.1.6)
Requirement already satisfied: fsspec in ./venv/lib/python3.12/site-packages (from torch->tensordict) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (1.11.1.6)
Requirement already satisfied: triton==3.3.0 in ./venv/lib/python3.12/site-packages (from torch->tensordict) (3.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch->tensordict) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.12/site-packages (from jinja2->torch->tensordict) (3.0.2)

In [2]:
from datetime import datetime, timezone
import numpy as np
import pandas as pd
import torch
from torch import nn
from tensordict import TensorDict

## Printando o 'head()' abaixo percebemos que a primeira coluna está separada da segunda com ';', portanto elas são concatenadas na criação do dataframe

In [3]:
df = pd.read_csv('data.csv', sep=",")
df.head()

,timestamp;400001,400017,400030,400040,400045,400052,400057,400059,400065,400069,...,409525,409526,409528,409529,413026,413845,413877,413878,414284,414694
0,01/01/2017 00:00;71.4,67.8,70.5,67.4,68.8,66.6,66.8,68.0,66.8,69.0,...,68.8,67.9,68.8,68.0,69.2,68.9,70.4,68.8,71.1,68.0
1,01/01/2017 00:05;71.6,67.5,70.6,67.5,68.7,66.6,66.8,67.8,66.5,68.2,...,68.4,67.3,68.4,67.6,70.4,68.8,70.1,68.4,70.8,67.4
2,01/01/2017 00:10;71.6,67.6,70.2,67.4,68.7,66.1,66.8,67.8,66.2,67.8,...,68.4,67.4,68.4,67.5,70.2,68.3,69.8,68.4,70.5,67.9
3,01/01/2017 00:15;71.1,67.5,70.3,68.0,68.5,66.7,66.6,67.7,65.9,67.8,...,68.5,67.5,68.5,67.5,70.4,68.7,70.2,68.4,70.8,67.6
4,01/01/2017 00:20;71.7,67.8,70.2,68.1,68.4,66.9,66.1,67.7,66.1,67.8,...,68.5,67.7,68.5,67.4,69.6,69.1,70.0,68.4,71.0,67.9

In [4]:
#Corrigindo o erro acima e consertanto a primeira coluna do dataframe
df[['timestamp', '400001']] = df['timestamp;400001'].str.split(';', expand=True)

df['400001'] = df['400001'].astype(float)


df['timestamp'] = pd.to_datetime(df['timestamp'], format='%d/%m/%Y %H:%M')

In [5]:
df = df.drop(columns=['timestamp;400001'])

In [6]:
if 'timestamp' in df.columns and '400001' in df.columns:

    cols = ['timestamp', '400001'] + [col for col in df.columns if col not in ['timestamp', '400001']]
    df = df[cols]

# Dataframe correto

In [7]:
df.head()

,timestamp,400001,400017,400030,400040,400045,400052,400057,400059,400065,...,409525,409526,409528,409529,413026,413845,413877,413878,414284,414694
0,2017-01-01 00:00:00,71.4,67.8,70.5,67.4,68.8,66.6,66.8,68.0,66.8,...,68.8,67.9,68.8,68.0,69.2,68.9,70.4,68.8,71.1,68.0
1,2017-01-01 00:05:00,71.6,67.5,70.6,67.5,68.7,66.6,66.8,67.8,66.5,...,68.4,67.3,68.4,67.6,70.4,68.8,70.1,68.4,70.8,67.4
2,2017-01-01 00:10:00,71.6,67.6,70.2,67.4,68.7,66.1,66.8,67.8,66.2,...,68.4,67.4,68.4,67.5,70.2,68.3,69.8,68.4,70.5,67.9
3,2017-01-01 00:15:00,71.1,67.5,70.3,68.0,68.5,66.7,66.6,67.7,65.9,...,68.5,67.5,68.5,67.5,70.4,68.7,70.2,68.4,70.8,67.6
4,2017-01-01 00:20:00,71.7,67.8,70.2,68.1,68.4,66.9,66.1,67.7,66.1,...,68.5,67.7,68.5,67.4,69.6,69.1,70.0,68.4,71.0,67.9

In [8]:
df.shape

(52116, 326)

In [9]:
#Existem valores NaT na coluna timestamp, nesse caso vou apenas remove-los
print(df[df['timestamp'].isna()])

      timestamp  400001  400017  400030  400040  400045  400052  400057  \
1638        NaT    72.5    38.6    49.6    45.4    53.8    66.4    57.8
3277        NaT    57.4    65.1    54.8    60.1    32.5    57.6    26.0
4916        NaT    69.9    63.2    66.9    61.0    61.9    66.7    67.2
6555        NaT    70.0    18.6    18.7    33.2    51.6    60.8    52.9
8194        NaT    71.6    64.8    61.9    59.9    61.4    66.7    64.7
9833        NaT    71.7    62.8    65.9    60.9    62.0    65.6    66.0
11472       NaT    68.0    57.1    58.6    52.2    60.1    63.3    62.1
13111       NaT    67.9    66.3    63.5    65.7    61.7    65.7    59.7
14750       NaT    77.6    64.3    68.0    61.1    70.5    67.5    66.0
16389       NaT    69.7    64.4    67.2    67.8    65.3    66.7    67.0
18028       NaT    63.7    64.7    58.6    64.6    63.2    67.6    57.6
19667       NaT    59.7    65.8    54.8    65.3    68.6    20.3    63.0
21306       NaT    70.8    64.1    67.5    67.3    70.6    67.5    66.9
22945       NaT    70.7    18.5    49.5    34.5    59.3    66.5    62.1
24584       NaT    60.1    65.9    54.8    67.0    30.7    64.1    58.1
26223       NaT    70.6    68.3    67.6    67.5    69.8    65.8    66.5
27862       NaT    72.1    56.8    39.8    58.1    69.1    68.0    64.0
29501       NaT    66.2    65.0    56.0    69.0    63.8    66.8    69.0
31140       NaT    70.8    63.1    66.2    67.9    68.5    67.8    66.4
32779       NaT    71.1    65.1    67.4    68.8    69.3    66.5    66.0
34418       NaT    68.1    62.1    55.6    68.1    63.2    64.0    61.6
36057       NaT    70.5    64.1    67.1    67.1    69.3    66.6    68.3
37696       NaT    71.5    66.2    67.0    68.8    70.1    68.3    62.9
39335       NaT    66.0    25.8    53.9    66.4    61.8    66.0    54.9
40974       NaT    35.9    64.9    10.7    68.1    60.8     9.4    44.3
42613       NaT    71.9    65.3    66.6    66.7    70.8    67.1    66.7
44252       NaT    69.9    60.7    61.7    68.2    61.4    64.5    60.1
45891       NaT    54.5    63.6    50.3    66.4    26.7    64.1    54.5
47530       NaT    69.9    64.2    66.8    67.7    70.5    67.8    65.9
49169       NaT    72.2    24.5    51.7    54.0    57.1    67.2     9.6
50808       NaT    69.2    62.4    51.6    54.5    62.0    68.8    57.9

       400059  400065  ...  409525  409526  409528  409529  413026  413845  \
1638     55.2    35.0  ...    63.4    65.2    60.1    60.4    64.1    57.5
3277     67.1    65.1  ...    44.1    38.2    68.9    63.6    63.0    29.0
4916     67.1    68.1  ...    69.8    64.8    67.6    61.7    67.3    60.3
6555     23.9    30.6  ...    67.3    64.2    18.8    35.6    61.7    49.2
8194     67.8    66.3  ...    66.7    69.0    63.4    60.5    71.7    66.4
9833     68.6    68.2  ...    64.4    63.1    63.4    60.2    67.3    66.0
11472    55.0    55.5  ...    65.7    63.0    59.2    57.5    65.8    61.0
13111    65.2    66.7  ...    64.9    64.4    64.1    63.8    62.3    67.7
14750    67.1    68.2  ...    69.5    68.6    65.6    61.3    63.7    68.9
16389    67.4    67.2  ...    67.7    66.1    66.7    63.0    63.8    62.3
18028    68.8    60.7  ...    68.9    65.8    65.0    59.6    65.6    66.2
19667    67.0    64.7  ...    66.5    63.3    65.7    60.8    63.6    45.7
21306    67.3    65.2  ...    68.9    64.9    67.3    62.1    68.3    61.5
22945    54.3    33.8  ...    68.4    66.5    57.9    59.7    65.1    51.9
24584    65.8    65.7  ...    62.6    61.3    67.7    62.6    64.4    31.1
26223    67.0    66.1  ...    68.4    65.3    69.4    61.1    64.2    67.9
27862    59.5    62.2  ...    68.5    67.2    63.6    60.5    65.2    60.8
29501    66.2    66.8  ...    66.1    65.0    61.7    58.1    61.9    59.9
31140    67.5    68.2  ...    67.6    63.6    66.4    61.6    68.0    60.8
32779    67.2    67.3  ...    69.1    66.9    68.5    64.0    70.7    62.4
34418    66.1    66.0  ...    64.2    65.9    64.7    58.7    66.7    59.1
36057    66.5    66.7  ...    68.3    65.1    66.6    61.4    70.5    60.3
37696    67.6    63.3  ...    64.2    65.8    62.5    60.6    68.9    60.9
39335    56.1    55.4  ...    66.7    63.3    66.6    60.3    61.3    59.3
40974    64.7    64.4  ...    52.8    52.4    66.6    63.8    66.0    35.2
42613    67.4    63.7  ...    67.8    64.2    66.9    63.2    70.7    62.5
44252    62.1    64.4  ...    64.3    64.5    60.9    58.3    64.6    60.7
45891    65.8    61.2  ...    61.1    60.8    64.6    59.7    60.7    31.6
47530    67.1    68.2  ...    67.1    63.4    67.0    61.8    69.4    63.4
49169    52.4    21.3  ...    64.4    66.2    25.7    60.4    67.2    68.0
50808    64.0    68.2  ...    63.6    66.6    60.9    55.7    59.6    58.3

       413877  413878  414284  414694
1638     66.8    65.2    68.6    66.7
3277     37.9    35.9    17.3    56.3
4916     69.1    67.8    72.0    66.2
6555     64.3    62.4    62.6    63.9
8194     69.3    65.4    71.1    66.1
9833     69.7    68.0    71.7    67.1
11472    65.3    62.6    65.9    64.4
13111    67.3    64.1    68.1    64.8
14750    72.0    69.9    72.3    69.1
16389    70.5    68.4    70.0    68.9
18028    70.2    66.2    67.8    64.3
19667    71.7    68.8    66.1    62.5
21306    69.0    68.2    69.0    66.8
22945    67.7    66.3    67.7    67.3
24584    67.6    62.2    67.9    63.0
26223    69.6    68.5    69.6    68.2
27862    68.1    68.7    70.4    67.7
29501    68.2    65.9    68.6    65.9
31140    69.9    67.9    69.0    68.3
32779    70.0    68.2    70.4    68.2
34418    70.9    59.4    67.7    64.9
36057    71.4    67.9    70.4    68.6
37696    69.3    65.0    68.7    67.3
39335    61.2    62.2    65.6    65.2
40974    32.2    41.8    66.8    54.3
42613    70.1    68.6    71.7    68.4
44252    62.3    61.9    69.4    64.6
45891    65.6    58.8    63.9    62.4
47530    70.4    67.8    67.0    66.1
49169    67.6    66.4    69.0    66.6
50808    60.9    63.6    71.5    63.6

[31 rows x 326 columns]

In [10]:
df = df[df['timestamp'].notna()]

In [11]:
df.shape

(52085, 326)

In [12]:
#Dataframe pronto
df.head()

,timestamp,400001,400017,400030,400040,400045,400052,400057,400059,400065,...,409525,409526,409528,409529,413026,413845,413877,413878,414284,414694
0,2017-01-01 00:00:00,71.4,67.8,70.5,67.4,68.8,66.6,66.8,68.0,66.8,...,68.8,67.9,68.8,68.0,69.2,68.9,70.4,68.8,71.1,68.0
1,2017-01-01 00:05:00,71.6,67.5,70.6,67.5,68.7,66.6,66.8,67.8,66.5,...,68.4,67.3,68.4,67.6,70.4,68.8,70.1,68.4,70.8,67.4
2,2017-01-01 00:10:00,71.6,67.6,70.2,67.4,68.7,66.1,66.8,67.8,66.2,...,68.4,67.4,68.4,67.5,70.2,68.3,69.8,68.4,70.5,67.9
3,2017-01-01 00:15:00,71.1,67.5,70.3,68.0,68.5,66.7,66.6,67.7,65.9,...,68.5,67.5,68.5,67.5,70.4,68.7,70.2,68.4,70.8,67.6
4,2017-01-01 00:20:00,71.7,67.8,70.2,68.1,68.4,66.9,66.1,67.7,66.1,...,68.5,67.7,68.5,67.4,69.6,69.1,70.0,68.4,71.0,67.9

In [13]:
def datetime_to_str(dt):
  return dt.strftime("%Y%m%d%H%M%S")

def str_to_datetime(dt):
  return datetime.strptime(dt, '%Y%m%d%H%M%S')

def to_pandas_datetime(values):
  return pd.to_datetime(values, format='%m/%d/%Y %H:%M')

def from_np_to_datetime(dt):
  dt = to_pandas_datetime(dt)
  return datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute)

def from_pd_to_datetime(dt):
  return datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute)
  
def from_datetime_to_pd(date : datetime):

  return to_pandas_datetime(np.datetime64(date.astimezone(None)))

In [14]:
class TemporalEmbedding(nn.Module):
  def __init__(self, dates, **kwargs):
    super().__init__()
    self.device = kwargs.get('device','cpu')
    self.dtype = kwargs.get('dtype',torch.float32)
    self.pi2 = torch.tensor([2 * torch.pi], dtype=self.dtype, device=self.device)
    self.week_minutes_rads = torch.tensor([(7 * 1440) * self.pi2], dtype=self.dtype, device=self.device)
    tmp_dict = {}
    self.length = 0
    for date in dates:
      tmp_dict[datetime_to_str(date)] = self.forward(date)
      self.length += 1 
    self.embeddings : TensorDict = TensorDict(tmp_dict) 

  def week_embedding(self, date):
      day_of_week = date.isocalendar()[2]  # Day of week (1: Monday, 7: Sunday)
      num = torch.tensor([day_of_week * 1440 + date.hour * 60 + date.minute], dtype=self.dtype, device=self.device)
      #Aqui a normalização esta errada, week_minutes não deve ser multiplicado por 2pi, 
      #o certo seria normalizar primeiro e depois transformar pra radiano
      return torch.sin(num / self.week_minutes_rads)

  def minute_embedding(self, date):
    minute_of_day = torch.tensor([(date.hour * 60 + date.minute)/ 1440], dtype=self.dtype, device=self.device)
    return torch.sin(minute_of_day * self.pi2)
  
  def forward(self, dt):
     date = from_pd_to_datetime(dt)
     we = self.week_embedding(date)
     me = self.minute_embedding(date)
     return torch.tensor([we, me], dtype=self.dtype, device=self.device)
  
  def __getitem__(self, date):
    if isinstance(date, np.datetime64):
      date =  from_np_to_datetime(date)
      return self.embeddings[datetime_to_str(date)]
    elif isinstance(date, datetime):
      return self.embeddings[datetime_to_str(date)]
    elif isinstance(date, int):
      return self.embeddings[date]
    else:
      raise Exception("Unknown index type")
    
  
  def all(self):
    ret = torch.empty(self.length, 2,
                        dtype=self.dtype, device=self.device)
    for it,emb in enumerate(self.embeddings.values(sort=True)):
      ret[it, :] = emb
    return ret
  
  def to(self, *args, **kwargs):
    self = super().to(*args, **kwargs)
    if isinstance(args[0], str):
      self.device = args[0]
    else:
      self.dtype = args[0]
    self.pi2 = self.pi2.to(*args, **kwargs)
    self.week_minutes_rads = self.week_minutes_rads.to(*args, **kwargs)
    return self

# Na classe abaixo eu corrigi isso

In [15]:
class TemporalEmbedding(nn.Module):
  def __init__(self, dates, **kwargs):
    super().__init__()
    self.device = kwargs.get('device','cpu')
    self.dtype = kwargs.get('dtype',torch.float32)
    self.pi2 = torch.tensor([2 * torch.pi], dtype=self.dtype, device=self.device)
    self.week_minutes = torch.tensor([(7 * 1440)], dtype=self.dtype, device=self.device)
    tmp_dict = {}
    self.length = 0
    for date in dates:
      tmp_dict[datetime_to_str(date)] = self.forward(date)
      self.length += 1 
    self.embeddings : TensorDict = TensorDict(tmp_dict) 

  def week_embedding(self, date):
      day_of_week = date.isocalendar()[2]  # Day of week (1: Monday, 7: Sunday)
      num = torch.tensor([day_of_week * 1440 + date.hour * 60 + date.minute], dtype=self.dtype, device=self.device)

      return torch.sin((num / self.week_minutes) * self.pi2)

  def minute_embedding(self, date):
    minute_of_day = torch.tensor([(date.hour * 60 + date.minute)/ 1440], dtype=self.dtype, device=self.device)
    return torch.sin(minute_of_day * self.pi2)
  
  def forward(self, dt):
     date = from_pd_to_datetime(dt)
     we = self.week_embedding(date)
     me = self.minute_embedding(date)
     return torch.tensor([we, me], dtype=self.dtype, device=self.device)
  
  def __getitem__(self, date):
    if isinstance(date, np.datetime64):
      date =  from_np_to_datetime(date)
      return self.embeddings[datetime_to_str(date)]
    elif isinstance(date, datetime):
      return self.embeddings[datetime_to_str(date)]
    elif isinstance(date, int):
      return self.embeddings[date]
    else:
      raise Exception("Unknown index type")
    
  
  def all(self):
    ret = torch.empty(self.length, 2,
                        dtype=self.dtype, device=self.device)
    for it,emb in enumerate(self.embeddings.values(sort=True)):
      ret[it, :] = emb
    return ret
  
  def to(self, *args, **kwargs):
    self = super().to(*args, **kwargs)
    if isinstance(args[0], str):
      self.device = args[0]
    else:
      self.dtype = args[0]
    self.pi2 = self.pi2.to(*args, **kwargs)
    self.week_minutes = self.week_minutes.to(*args, **kwargs)
    return self

In [ ]:
timestamps = df['timestamp']  
#timestamps = df['timestamp'][:5]

temporal_embedding = TemporalEmbedding(timestamps, device='cpu')



all_embeddings = temporal_embedding.all()

In [ ]:
data = []
for ts in timestamps:
    emb = temporal_embedding[ts]
    data.append([ts, emb[0].item(), emb[1].item()])

df_emb = pd.DataFrame(data, columns=['timestamp', 'embedding_week', 'embedding_minute'])
print(df_emb.head())

### Aqui vou pegar um embedding arbitrario, no caso de 00:05:00, e checar se existem outros valores de timestamp com o mesmo embedding
### embeddin_week = 0.003116777 e embeddin_minute = 0.021815

In [ ]:
eps = 1e-6  

filtro_aproximado = (
    (df_emb["embedding_week"].sub(0.003116777).abs() < eps) &
    (df_emb["embedding_minute"].sub(0.021815).abs() < eps)
)

timestamps_filtrados = df_emb.loc[filtro_aproximado, "timestamp"]
print(timestamps_filtrados)
# Aqui é possível ver que os embeddings de 00:05:00 e 11:55:00 são iguais pois a funçào sin é
# cíclica e os dois timestamps são equidistantes de 00:00:00 e

# Abaixo eu refiz a classe e para contornar esse problema foi utilizado também a função cos que também é cíclica mas como tem uma fase diferente de sen, soluciona esse problema

In [ ]:
class TemporalEmbedding(nn.Module):
  def __init__(self, dates, **kwargs):
    super().__init__()
    self.device = kwargs.get('device','cpu')
    self.dtype = kwargs.get('dtype',torch.float32)
    self.pi2 = torch.tensor([2 * torch.pi], dtype=self.dtype, device=self.device)
    self.day_minutes = torch.tensor([(1440)], dtype=self.dtype, device=self.device )
    self.week_minutes = torch.tensor([(7 * 1440)], dtype=self.dtype, device=self.device)
    tmp_dict = {}
    self.length = 0
    for date in dates:
      tmp_dict[datetime_to_str(date)] = self.forward(date)
      self.length += 1 
    self.embeddings : TensorDict = TensorDict(tmp_dict) 

  def week_embedding(self, date):
    day_of_week = date.isocalendar()[2]  # Day of week (1: Monday, 7: Sunday)
    
    num = torch.tensor([day_of_week * 1440 + date.hour * 60 + date.minute], dtype=self.dtype, device=self.device)
    angle = num * self.pi2 / self.week_minutes
    return torch.sin(angle), torch.cos(angle)

  def minute_embedding(self, date):
    minute_of_day = torch.tensor([(date.hour * 60 + date.minute)/ 1440], dtype=self.dtype, device=self.device)
    angle = minute_of_day * self.pi2
    return torch.sin(angle), torch.cos(angle)
  
  def forward(self, dt):
     date = from_pd_to_datetime(dt)
     we_sin, we_cos = self.week_embedding(date)
     me_sin, me_cos = self.minute_embedding(date)
     return torch.stack([we_sin, we_cos, me_sin, me_cos]).squeeze()

  
  def __getitem__(self, date):
    if isinstance(date, np.datetime64):
      date =  from_np_to_datetime(date)
      return self.embeddings[datetime_to_str(date)]
    elif isinstance(date, datetime):
      return self.embeddings[datetime_to_str(date)]
    elif isinstance(date, int):
      return self.embeddings[date]
    else:
      raise Exception("Unknown index type")
    
  
  def all(self):
    ret = torch.empty(self.length, 4, dtype=self.dtype, device=self.device)
    for it,emb in enumerate(self.embeddings.values(sort=True)):
      ret[it, :] = emb
    return ret
  
  def to(self, *args, **kwargs):
    self = super().to(*args, **kwargs)
    if isinstance(args[0], str):
      self.device = args[0]
    else:
      self.dtype = args[0]
    self.pi2 = self.pi2.to(*args, **kwargs)
    self.week_minutes = self.week_minutes.to(*args, **kwargs)
    return self

In [ ]:


timestamps = df['timestamp']  
#timestamps = df['timestamp'][:5]


temporal_embedding = TemporalEmbedding(timestamps, device='cpu')



all_embeddings = temporal_embedding.all()

In [ ]:
data = []
for ts in timestamps:
    emb = temporal_embedding[ts]
    data.append([ts, emb[0].item(), emb[1].item()])

df_emb = pd.DataFrame(data, columns=['timestamp', 'embedding_week', 'embedding_minute'])
print(df_emb.head())

In [ ]:
eps = 1e-6  

filtro_aproximado = (
    (df_emb["embedding_week"].sub(0.003116777).abs() < eps) &
    (df_emb["embedding_minute"].sub(0.999995).abs() < eps)
)

timestamps_filtrados = df_emb.loc[filtro_aproximado, "timestamp"]
print(timestamps_filtrados)
# Corrigido, é possível verificar que somente os mesmos timestamps tem essa representação de embedding.